language: node_js
node_js:
  - 8
install: npm install
script: bash ./travis/test.sh
cache:
  directories:
    - node_modules
branches:
  except:
  - unreviewed/*
  only:
  - indev
sudo: false
dist: trusty
after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
