#!/bin/bash

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".js$")

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

echo "Validating Javascript:"

"$(git rev-parse --show-toplevel)/node_modules/.bin/eslint" "$STAGED_FILES"

if [[ "$?" == 0 ]]; then
  echo -e "\t\033[32mESLint Passed: $STAGED_FILES\033[0m"
else
  # echo -e "\t\033[41mESLint Failed: $STAGED_FILES\033[0m"
  PASS=false
fi

if ! $PASS; then
  echo -e "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again."
  exit 1
else
  echo -e "\033[42mCOMMIT SUCCEEDED\033[0m"
fi

exit $?
