#!/bin/bash

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".js$" | tr '\n' ' ')

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

echo "Validating Javascript:"

ESLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/eslint"

"$ESLINT" "$STAGED_FILES"
if [[ "$?" == 0 ]]; then
  echo -e "\t\033[32mESLint Passed: $STAGED_FILES\033[0m"
else
  PASS=false
fi

if ! $PASS; then
  echo -e "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again."
  exit 1
fi

if [[ "$?" != 0 ]]; then
  exit $?
fi

echo "Creating docs"
jsdoc2md src/*.js --private > docs/README.md

if [[ "$?" != 0 ]]; then
  exit $?
fi

git add docs/

exit $?
