#!/bin/bash

STAGED_SCRIPTS=$(git diff --cached --name-only --diff-filter=ACM | grep ".js$" | tr '\n' ' ')
STAGED_DATA=$(git diff --cached --name-only --diff-filter=ACM | grep ".json$" | tr '\n' ' ')

# if [[ "$STAGED_SCRIPTS" = "" ]]; then
#   exit 0
# fi

# if [[ "$STAGED_SCRIPTS" != "" ]]; then
#   PASS=true
# 
#   echo "Validating Javascript:"
# 
#   ESLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/eslint"
# 
#   "$ESLINT" "$STAGED_SCRIPTS"
#   if [[ "$?" == 0 ]]; then
#     echo -e "\t\033[32mESLint Passed: $STAGED_SCRIPTS\033[0m"
#   else
#     PASS=false
#   fi
# 
#   if ! $PASS; then
#     echo -e "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again."
#     exit 1
#   fi
# 
#   if [[ "$?" != 0 ]]; then
#     exit $?
#   fi
# fi

if [[ "$STAGED_SCRIPTS" != "" || "$STAGED_DATA" != "" ]]; then
  echo "Linting"
  npm run lint
  if [[ "$?" != 0 ]]; then
    exit 1
  fi

  echo "Creating docs"
  bash .hooks/make-docs.sh
  if [[ "$?" != 0 ]]; then
    exit 1
  fi

  git add docs/

  exit $?
else
  exit 0
fi
